version: '3.10'

services:
  db:
    image: django-lab5-tkvs-2
    volumes:
    - /data/db:/root/db
    environment:
    - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - ./metanit:/metanit
    ports:
     - "8003:8000"
    depends_on:
     - db
